// function multiplesOf3and5(number) {
//     //배수 찾는 코드 

//     // i % 3 == 0 3배수
//     // i % 5 == 0 5배수
//     //퍼센트를 써라
//     let zero = 0;
//     // for (let i = 1; i > 0; i--) {
//     // let addingNumber = "";
//     for (let i = 1; i <= number - 1; i++) {
//         //유저가 부른 숫자 까지 돌게하기
//         if (i % 3 == 0 || i % 5 == 0) {

//             //let addingNumber = zero + i;
//             zero += i;
//             //console.log(addingNumber);
//         }
//         //console.log(i);
//     }
//     console.log(zero);
//     return zero;
// }
// // 마지막까지 나왔던 숫자들 다 더하는걸 만들어야되는데
// console.log(multiplesOf3and5(10));

// function addTwoParameter(a,b) {
//     return a + b
// }

// console.log(addTwoParameter(1,2))


// Problem 2: Even Fibonacci Numbers
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.

// function fiboEvenSum(n) {

//     return true;
// }

// fiboEvenSum(10);
const a = new String(123);
console.log(a);